class RvrStreamingServices:
    color_detection = 'ColorDetection'
    ambient_light = 'AmbientLight'
    quaternion = 'Quaternion'
    imu = 'IMU'
    accelerometer = 'Accelerometer'
    gyroscope = 'Gyroscope'
    locator = 'Locator'
    velocity = 'Velocity'
    speed = 'Speed'
    core_time = 'CoreTime'
    encoders = 'Encoders'
