#!/usr/bin/env python3
# This file is automatically generated!
# Toy Name:           Sphero Mock
# Prefix:             MK
# Timestamp:          01/23/2019 @ 18:37:41.354455 (UTC)

from enum import IntEnum
