#!/usr/bin/env python3
# This file is automatically generated!
# Toy Name:           Sphero RVR
# Prefix:             RV
# Timestamp:          02/08/2019 @ 00:55:35.189518 (UTC)

from enum import IntEnum
