#!/usr/bin/env python3
# This file is automatically generated!
# Toy Name:           Sphero RVR
# Prefix:             RV
# Timestamp:          02/08/2019 @ 17:14:09.088145 (UTC)

from enum import IntEnum
