#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x10-api_and_shell.json
# Device ID:          0x10
# Device Name:        api_and_shell
# Timestamp:          01/23/2019 @ 18:37:41.328725 (UTC)

from enum import IntEnum


class CommandsEnum(IntEnum):
    echo = 0x00
    get_api_protocol_version = 0x01
    send_command_to_shell = 0x02
    send_string_to_console = 0x03
    get_supported_dids = 0x05
    get_supported_cids = 0x06
