#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x10-api_and_shell.json
# Device ID:          0x10
# Device Name:        api_and_shell
# Timestamp:          02/21/2019 @ 00:09:09.858185 (UTC)

from enum import IntEnum


class CommandsEnum(IntEnum):
    echo = 0x00
    get_api_protocol_version = 0x01
    get_supported_dids = 0x05
    get_supported_cids = 0x06
