#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x1F-factory_testing.json
# Device ID:          0x1F
# Device Name:        factory_test
# Timestamp:          02/08/2019 @ 00:55:35.166664 (UTC)

from enum import IntEnum


class CommandsEnum(IntEnum):
    set_test_fixture_result = 0x11
    get_test_fixture_result = 0x12
    get_factory_mode_challenge = 0x13
    enter_factory_mode = 0x14
    exit_factory_mode = 0x15
    get_chassis_id = 0x27
    enable_extended_life_test = 0x31
    get_factory_mode_status = 0x34
