#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x1D-secondary_mcu_firmware_update.json
# Device ID:          0x1D
# Device Name:        firmware
# Timestamp:          01/23/2019 @ 18:37:41.333781 (UTC)

from enum import IntEnum


class CommandsEnum(IntEnum):
    jump_to_bootloader = 0x05
