#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x1D-secondary_mcu_firmware_update.json
# Device ID:          0x1D
# Device Name:        firmware
# Timestamp:          02/08/2019 @ 00:55:35.169517 (UTC)

from enum import IntEnum


class CommandsEnum(IntEnum):
    jump_to_bootloader = 0x05
