#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x11-system_info.json
# Device ID:          0x11
# Device Name:        system_info
# Timestamp:          02/08/2019 @ 17:14:09.074728 (UTC)

from enum import IntEnum


__all__ = ['ConfigBlockWriteCodesEnum',
           'DeviceModesEnum',
           'ApplicationIndexesEnum']


class CommandsEnum(IntEnum):
    get_main_application_version = 0x00
    get_bootloader_version = 0x01
    get_board_revision = 0x03
    get_mac_address = 0x06
    get_nordic_temperature = 0x0E
    application_ready_notify = 0x10
    get_stats_id = 0x13
    application_alive_notify = 0x1E
    get_processor_name = 0x1F
    get_boot_reason = 0x20
    get_last_error_info = 0x21
    request_l1_diagnostics = 0x26
    write_config_block = 0x2B
    get_config_block = 0x2C
    set_config_block = 0x2D
    erase_config_block = 0x2E
    get_swd_locking_status = 0x30
    set_swd_locking = 0x31
    get_manufacturing_date = 0x33
    set_manufacturing_date = 0x34
    set_sku = 0x37
    get_sku = 0x38


class ConfigBlockWriteCodesEnum(IntEnum):
    ''' '''
    CB_SUCCESS = 0  #: 
    CB_BUSY = 1  #: 
    CB_FS_ERROR = 2  #: 


class DeviceModesEnum(IntEnum):
    ''' '''
    factory_mode = 0  #: 
    user_play_test_mode = 1  #: 
    user_out_of_box_mode = 2  #: 
    user_full_mode = 3  #: 


class ApplicationIndexesEnum(IntEnum):
    ''' '''
    bootloader = 0  #: 
    main_application = 1  #: 
