#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x16-driving.json
# Device ID:          0x16
# Device Name:        drive
# Timestamp:          02/21/2019 @ 00:09:09.860015 (UTC)

from spheroboros.common.commands.drive import CommandsEnum
from spheroboros.common.devices import DevicesEnum
from spheroboros.common.parameter import Parameter


def raw_motors(self, left_mode, left_speed, right_mode, right_speed, target, timeout=None):
    return self._dal.send_command(
        DevicesEnum.drive,
        CommandsEnum.raw_motors,
        target,
        timeout,
        inputs=[
            Parameter(
                name='leftMode',
                data_type='uint8_t',
                index=0,
                value=left_mode,
                size=1
            ),
            Parameter(
                name='leftSpeed',
                data_type='uint8_t',
                index=1,
                value=left_speed,
                size=1
            ),
            Parameter(
                name='rightMode',
                data_type='uint8_t',
                index=2,
                value=right_mode,
                size=1
            ),
            Parameter(
                name='rightSpeed',
                data_type='uint8_t',
                index=3,
                value=right_speed,
                size=1
            ),
        ],
    )


def reset_yaw(self, target, timeout=None):
    return self._dal.send_command(
        DevicesEnum.drive,
        CommandsEnum.reset_yaw,
        target,
        timeout,
    )


def drive_with_heading(self, speed, heading, flags, target, timeout=None):
    return self._dal.send_command(
        DevicesEnum.drive,
        CommandsEnum.drive_with_heading,
        target,
        timeout,
        inputs=[
            Parameter(
                name='speed',
                data_type='uint8_t',
                index=0,
                value=speed,
                size=1
            ),
            Parameter(
                name='heading',
                data_type='int16_t',
                index=1,
                value=heading,
                size=1
            ),
            Parameter(
                name='flags',
                data_type='uint8_t',
                index=2,
                value=flags,
                size=1
            ),
        ],
    )
