#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x1D-secondary_mcu_firmware_update.json
# Device ID:          0x1D
# Device Name:        firmware
# Timestamp:          01/23/2019 @ 18:37:41.333717 (UTC)

from spheroboros.common.commands.firmware import CommandsEnum
from spheroboros.common.devices import DevicesEnum
from spheroboros.common.parameter import Parameter


def jump_to_bootloader(self, target, timeout=None):
    return self._dal.send_command(
        DevicesEnum.firmware,
        CommandsEnum.jump_to_bootloader,
        target,
        timeout,
    )
