#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x10-api_and_shell.json
# Device ID:          0x10
# Device Name:        api_and_shell
# Timestamp:          07/08/2020 @ 22:29:07.236029 (UTC)

from enum import IntEnum


class CommandsEnum(IntEnum): 
    echo = 0x00
