#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x10-api_and_shell.json
# Device ID:          0x10
# Device Name:        api_and_shell
# Timestamp:          04/03/2020 @ 19:24:05.555292 (UTC)

from enum import IntEnum


class CommandsEnum(IntEnum): 
    echo = 0x00
