#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x19-peer_connection.json
# Device ID:          0x19
# Device Name:        connection
# Timestamp:          04/03/2020 @ 19:24:05.520937 (UTC)

from enum import IntEnum


class CommandsEnum(IntEnum): 
    get_bluetooth_advertising_name = 0x05
