#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x16-driving.json
# Device ID:          0x16
# Device Name:        drive
# Timestamp:          10/12/2019 @ 01:43:14.085678 (UTC)

from enum import IntEnum


__all__ = ['RawMotorModesEnum',
           'MotorIndexesEnum',
           'DriveFlagsBitmask']


class CommandsEnum(IntEnum): 
    raw_motors = 0x01
    reset_yaw = 0x06
    drive_with_heading = 0x07
    enable_motor_stall_notify = 0x25
    motor_stall_notify = 0x26
    enable_motor_fault_notify = 0x27
    motor_fault_notify = 0x28
    get_motor_fault_state = 0x29


class RawMotorModesEnum(IntEnum):
    off = 0
    forward = 1
    reverse = 2


class MotorIndexesEnum(IntEnum):
    left_motor_index = 0
    right_motor_index = 1


class DriveFlagsBitmask(IntEnum):
    none = 0
    drive_reverse = 1
    boost = 2
    fast_turn = 4
    left_direction = 8
    right_direction = 16
    enable_drift = 32
