#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x1A-user_io.json
# Device ID:          0x1A
# Device Name:        io
# Timestamp:          08/21/2019 @ 17:53:39.432182 (UTC)

from enum import IntEnum


__all__ = ['UsbConnectionStatusEnum',
           'AudioPlaybackModesEnum',
           'SpecdrumsColorPaletteIndiciesEnum']


class CommandsEnum(IntEnum): 
    set_all_leds_with_32_bit_mask = 0x1A
    set_led_matrix_one_color = 0x2F
    save_led_matrix_animation_frame = 0x30
    save_led_matrix_animation = 0x31
    play_led_matrix_animation = 0x32
    play_led_matrix_animation_frame = 0x33
    get_led_matrix_animation_frames = 0x34
    delete_led_matrix_animations_and_frames = 0x35
    pause_led_matrix = 0x36
    resume_led_matrix = 0x37
    reset_led_matrix = 0x38
    led_matrix_animation_complete_notify = 0x3F
    assign_frames_to_animation = 0x40
    save_led_matrix_animation_without_frames = 0x41
    play_led_matrix_animation_with_loop_option = 0x43
    get_active_color_palette = 0x44
    set_active_color_palette = 0x45
    get_color_identification_report = 0x46
    load_color_palette = 0x47
    save_color_palette = 0x48


class UsbConnectionStatusEnum(IntEnum):
    ''' '''
    unknown = 0  #: USB Connection Status is unknown.
    connected_but_not_ready = 1  #: USB is connected to a Device, but not ready for communication.
    connected_and_ready = 2  #: USB is connected and ready for communication!
    disconnected = 3  #: USB is disconnected!


class AudioPlaybackModesEnum(IntEnum):
    ''' '''
    play_immediately = 0  #: 
    play_only_if_not_playing = 1  #: 
    play_after_current_sound = 2  #: 


class SpecdrumsColorPaletteIndiciesEnum(IntEnum):
    ''' '''
    default = 0  #: 
    midi = 1  #: 
