#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x18-sensors.json
# Device ID:          0x18
# Device Name:        sensor
# Timestamp:          07/02/2019 @ 21:20:31.346003 (UTC)

from enum import IntEnum


__all__ = ['CollisionDetectionMethodsEnum',
           'CliffDetectionSensorLocationsBitMask',
           'GyroMaxFlagsBitMask',
           'CollisionDetectedAxisBitMask',
           'InfraredSensorLocationsBitMask']


class CommandsEnum(IntEnum):
    set_sensor_streaming_mask = 0x00
    get_sensor_streaming_mask = 0x01
    sensor_streaming_data_notify = 0x02
    get_encoder_counts = 0x09
    get_euler_angles = 0x0A
    get_gyro_degrees_per_second = 0x0B
    set_extended_sensor_streaming_mask = 0x0C
    get_extended_sensor_streaming_mask = 0x0D
    enable_gyro_max_notify = 0x0F
    gyro_max_notify = 0x10
    configure_collision_detection = 0x11
    collision_detected_notify = 0x12
    get_bot_to_bot_infrared_readings = 0x22
    start_robot_to_robot_infrared_broadcasting = 0x27
    stop_robot_to_robot_infrared_broadcasting = 0x29
    send_robot_to_robot_infrared_message = 0x2A
    listen_for_robot_to_robot_infrared_message = 0x2B
    robot_to_robot_infrared_message_received_notify = 0x2C
    get_ambient_light_sensor_value = 0x30
    enable_color_detection_notification = 0x35
    color_detection_notify = 0x36
    get_current_detected_color_reading = 0x37
    enable_color_detection = 0x38


class CollisionDetectionMethodsEnum(IntEnum):
    ''' '''
    no_collision_detection = 0  #: 
    accelerometer_based_detection = 1  #: 
    accelerometer_based_with_extra_filtering = 2  #: 
    hybrid_accelerometer_and_control_system_detection = 3  #: 


class CliffDetectionSensorLocationsBitMask(IntEnum):
    ''' '''
    front_left = 1 #: 
    front_right = 2 #: 
    back_left = 4 #: 
    back_right = 8 #: 


class GyroMaxFlagsBitMask(IntEnum):
    ''' '''
    max_plus_x = 1 #: 
    max_minus_x = 2 #: 
    max_plus_y = 4 #: 
    max_minus_y = 8 #: 
    max_plus_z = 16 #: 
    max_minus_z = 32 #: 


class CollisionDetectedAxisBitMask(IntEnum):
    ''' '''
    x_axis = 1 #: 
    y_axis = 2 #: 


class InfraredSensorLocationsBitMask(IntEnum):
    ''' '''
    front_left = 1 #: 
    front_right = 2 #: 
    back_right = 4 #: 
    back_left = 8 #: 
