#!/usr/bin/env python3
# This file is automatically generated!
# Source File:        0x13-power.json
# Device ID:          0x13
# Device Name:        power
# Timestamp:          07/02/2019 @ 22:49:01.161660 (UTC)

from sphero_sdk.common.enums.power_enums import CommandsEnum
from sphero_sdk.common.devices import DevicesEnum
from sphero_sdk.common.parameter import Parameter


def enter_deep_sleep(seconds_until_deep_sleep, target, timeout):
    return {
        'did': DevicesEnum.power,
        'cid': CommandsEnum.enter_deep_sleep,
        'target': target,
        'timeout': timeout,
        'inputs': [
            Parameter(
                name='secondsUntilDeepSleep',
                data_type='uint8_t',
                index=0,
                value=seconds_until_deep_sleep,
                size=1
            ),
        ],
    }


def enter_soft_sleep(target, timeout):
    return {
        'did': DevicesEnum.power,
        'cid': CommandsEnum.enter_soft_sleep,
        'target': target,
        'timeout': timeout,
    }


def wake(target, timeout):
    return {
        'did': DevicesEnum.power,
        'cid': CommandsEnum.wake,
        'target': target,
        'timeout': timeout,
    }


def get_battery_percentage(target, timeout):
    return {
        'did': DevicesEnum.power,
        'cid': CommandsEnum.get_battery_percentage,
        'target': target,
        'timeout': timeout,
        'outputs': [
            Parameter(
                name='percentage',
                data_type='uint8_t',
                index=0,
                size=1,
            ),
        ]
    }


def get_battery_voltage_state(target, timeout):
    return {
        'did': DevicesEnum.power,
        'cid': CommandsEnum.get_battery_voltage_state,
        'target': target,
        'timeout': timeout,
        'outputs': [
            Parameter(
                name='state',
                data_type='uint8_t',
                index=0,
                size=1,
            ),
        ]
    }


def on_will_sleep_notify(target, timeout):
    return {
        'did': DevicesEnum.power,
        'cid': CommandsEnum.will_sleep_notify,
        'target': target,
        'timeout': timeout,
    }


def on_did_sleep_notify(target, timeout):
    return {
        'did': DevicesEnum.power,
        'cid': CommandsEnum.did_sleep_notify,
        'target': target,
        'timeout': timeout,
    }


def enable_battery_voltage_state_change_notify(is_enabled, target, timeout):
    return {
        'did': DevicesEnum.power,
        'cid': CommandsEnum.enable_battery_voltage_state_change_notify,
        'target': target,
        'timeout': timeout,
        'inputs': [
            Parameter(
                name='isEnabled',
                data_type='bool',
                index=0,
                value=is_enabled,
                size=1
            ),
        ],
    }


def on_battery_voltage_state_change_notify(target, timeout):
    return {
        'did': DevicesEnum.power,
        'cid': CommandsEnum.battery_voltage_state_change_notify,
        'target': target,
        'timeout': timeout,
        'outputs': [
            Parameter(
                name='state',
                data_type='uint8_t',
                index=0,
                size=1,
            ),
        ]
    }
